[project]
name = "llm-nvcc"
version = "0.1.0"
description = "Projeto chatbook com modelos variados"
authors = [
    {name = "Michael Borges",email = "michaelborges21@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter (>=1.1.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
